services:
  budget-app-frontend:
    image: budget-app-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - "VITE_API_URL=http://localhost:3000/api"
    container_name: budget-app-frontend
    ports:
      - '80:80'